### ISSUE TITLE
button event not working on built app

### ISSUE THREAD

**Issue by roydhenderson** [richlewis42/electron-flask#3]
Hey, great demo, but when I package the app the button event/callback no longer works. Any ideas? Thanks!

update: seems to be cos api is not being served when packaged.

https://github.com/richlewis42/electron-flask/blob/08747d7c21b9ab4731e83f816de19494c6484d0e/src/index.html#L13

**Comment by lewisacidic** [comment]
Hi!  Sorry, I haven't looked at electron since I did this.  Yeah, looks like the flask server needs to be started from within the app - I clearly didn't get that far! I probably don't have time to look to get this working, but you might be able to just spawn the subprocess straight in the index.html for a super dirty example.
